#!/bin/bash

# Tests and builds the application.

set -e -x

err="$(go fmt ./...)"
if [[ -n $err ]]; then echo "go fmt: ${err}" && exit 1; fi

err="$(go vet ./...)"
if [[ -n $err ]]; then echo "go vet: ${err}" && exit 2; fi

go test -v ./...
go test -v -race ./...

ldflags="-X main.version=$(git describe --tags)"
go build -v -ldflags "$ldflags"
GOOS=darwin GOARCH=amd64 go build -v -o ntwrk-darwin-amd64 -ldflags "$ldflags"
GOOS=linux GOARCH=amd64 go build -v -o ntwrk-linux-amd64 -ldflags "$ldflags"

exit 0
